const layerOneElements = {
  nodes: [
    {
      data: {
        id: "6855",
        shared_name: "behavior",
        name: "behavior",
        exposure_cate: "exposures",
        outcome_cate: "",
        SUID: 6855,
        selected: false,
      },
      position: {
        x: 93.25567839239201,
        y: -53.841191023308724,
      },
      selected: false,
    },
    {
      data: {
        id: "6853",
        shared_name: "biomarker",
        name: "biomarker",
        exposure_cate: "both",
        outcome_cate: "both",
        SUID: 6853,
        selected: false,
      },
      position: {
        x: 93.25567839239207,
        y: 53.84119102330868,
      },
      selected: false,
    },
    {
      data: {
        id: "6851",
        shared_name: "disease",
        name: "disease",
        exposure_cate: "both",
        outcome_cate: "both",
        SUID: 6851,
        selected: false,
      },
      position: {
        x: -5.6843418860808015e-14,
        y: -107.68238204661739,
      },
      selected: false,
    },
    {
      data: {
        id: "6849",
        shared_name: "psychosocial",
        name: "psychosocial",
        exposure_cate: "both",
        outcome_cate: "both",
        SUID: 6849,
        selected: false,
      },
      position: {
        x: -93.25567839239207,
        y: -53.84119102330865,
      },
      selected: false,
    },
    {
      data: {
        id: "6847",
        shared_name: "chemical",
        name: "chemical",
        exposure_cate: "both",
        outcome_cate: "both",
        SUID: 6847,
        selected: false,
      },
      position: {
        x: -93.2556783923921,
        y: 53.84119102330874,
      },
      selected: false,
    },
    {
      data: {
        id: "6845",
        shared_name: "physical",
        name: "physical",
        exposure_cate: "exposures",
        outcome_cate: "",
        SUID: 6845,
        selected: false,
      },
      position: {
        x: 0.0,
        y: 107.68238204661748,
      },
      selected: false,
    },
    {
      data: {
        id: "6843",
        shared_name: "Exposures",
        name: "Exposures",
        exposure_cate: "exposures",
        outcome_cate: "",
        SUID: 6843,
        selected: false,
      },
      position: {
        x: 88.55725510779016,
        y: -158.67226312269312,
      },
      selected: false,
    },
    {
      data: {
        id: "6841",
        shared_name: "Exposure and Outcome",
        name: "Exposure and Outcome",
        exposure_cate: "both",
        outcome_cate: "",
        SUID: 6841,
        selected: false,
      },
      position: {
        x: 88.54904024958283,
        y: -115.3073795576208,
      },
      selected: false,
    },
  ],
  edges: [
    {
      data: {
        id: "6883",
        source: "6855",
        target: "6853",
        "": 0,
        shared_name: "behavior (interacts with) biomarker",
        shared_interaction: "interacts with",
        name: "behavior (interacts with) biomarker",
        interaction: "interacts with",
        edge_id: 1,
        SUID: 6883,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6881",
        source: "6855",
        target: "6851",
        "": 1,
        shared_name: "behavior (interacts with) disease",
        shared_interaction: "interacts with",
        name: "behavior (interacts with) disease",
        interaction: "interacts with",
        edge_id: 2,
        SUID: 6881,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6879",
        source: "6853",
        target: "6853",
        "": 2,
        shared_name: "biomarker (interacts with) biomarker",
        shared_interaction: "interacts with",
        name: "biomarker (interacts with) biomarker",
        interaction: "interacts with",
        edge_id: 3,
        SUID: 6879,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6877",
        source: "6853",
        target: "6851",
        "": 3,
        shared_name: "biomarker (interacts with) disease",
        shared_interaction: "interacts with",
        name: "biomarker (interacts with) disease",
        interaction: "interacts with",
        edge_id: 4,
        SUID: 6877,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6875",
        source: "6853",
        target: "6849",
        "": 4,
        shared_name: "biomarker (interacts with) psychosocial",
        shared_interaction: "interacts with",
        name: "biomarker (interacts with) psychosocial",
        interaction: "interacts with",
        edge_id: 5,
        SUID: 6875,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6873",
        source: "6851",
        target: "6853",
        "": 8,
        shared_name: "disease (interacts with) biomarker",
        shared_interaction: "interacts with",
        name: "disease (interacts with) biomarker",
        interaction: "interacts with",
        edge_id: 9,
        SUID: 6873,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6871",
        source: "6849",
        target: "6853",
        "": 11,
        shared_name: "psychosocial (interacts with) biomarker",
        shared_interaction: "interacts with",
        name: "psychosocial (interacts with) biomarker",
        interaction: "interacts with",
        edge_id: 12,
        SUID: 6871,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6869",
        source: "6849",
        target: "6851",
        "": 12,
        shared_name: "psychosocial (interacts with) disease",
        shared_interaction: "interacts with",
        name: "psychosocial (interacts with) disease",
        interaction: "interacts with",
        edge_id: 13,
        SUID: 6869,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6867",
        source: "6849",
        target: "6849",
        "": 13,
        shared_name: "psychosocial (interacts with) psychosocial",
        shared_interaction: "interacts with",
        name: "psychosocial (interacts with) psychosocial",
        interaction: "interacts with",
        edge_id: 14,
        SUID: 6867,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6865",
        source: "6847",
        target: "6853",
        "": 5,
        shared_name: "chemical (interacts with) biomarker",
        shared_interaction: "interacts with",
        name: "chemical (interacts with) biomarker",
        interaction: "interacts with",
        edge_id: 6,
        SUID: 6865,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6863",
        source: "6847",
        target: "6851",
        "": 6,
        shared_name: "chemical (interacts with) disease",
        shared_interaction: "interacts with",
        name: "chemical (interacts with) disease",
        interaction: "interacts with",
        edge_id: 7,
        SUID: 6863,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6861",
        source: "6847",
        target: "6849",
        "": 7,
        shared_name: "chemical (interacts with) psychosocial",
        shared_interaction: "interacts with",
        name: "chemical (interacts with) psychosocial",
        interaction: "interacts with",
        edge_id: 8,
        SUID: 6861,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6859",
        source: "6845",
        target: "6853",
        "": 9,
        shared_name: "physical (interacts with) biomarker",
        shared_interaction: "interacts with",
        name: "physical (interacts with) biomarker",
        interaction: "interacts with",
        edge_id: 10,
        SUID: 6859,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "6857",
        source: "6845",
        target: "6847",
        "": 10,
        shared_name: "physical (interacts with) chemical",
        shared_interaction: "interacts with",
        name: "physical (interacts with) chemical",
        interaction: "interacts with",
        edge_id: 11,
        SUID: 6857,
        selected: false,
      },
      selected: false,
    },
  ],
};

export default layerOneElements;
