const elements = {
  nodes: [
    {
      data: {
        id: "356",
        shared_name: "Exposure and Outcome",
        exposure_attr: "both",
        centrality: 0.0,
        outcome_attr: "",
        name: "Exposure and Outcome",
        SUID: 356,
        selected: false,
      },
      position: {
        x: 1545.1182037789133,
        y: -1557.5010068475683,
      },
      selected: false,
    },
    {
      data: {
        id: "354",
        shared_name: "Outcome",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "",
        name: "Outcome",
        SUID: 354,
        selected: false,
      },
      position: {
        x: 1535.6232380167555,
        y: -1752.3760907515323,
      },
      selected: false,
    },
    {
      data: {
        id: "352",
        shared_name: "Exposure",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "Exposure",
        SUID: 352,
        selected: false,
      },
      position: {
        x: 1525.8246745279903,
        y: -1937.6655256146285,
      },
      selected: false,
    },
    {
      data: {
        id: "350",
        shared_name: "BMI",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "BMI",
        SUID: 350,
        selected: false,
      },
      position: {
        x: -1814.521711507447,
        y: -379.28614507965966,
      },
      selected: false,
    },
    {
      data: {
        id: "348",
        shared_name: "cholesterol level",
        exposure_attr: "both",
        centrality: 0.0029403327596098,
        outcome_attr: "both",
        name: "cholesterol level",
        SUID: 348,
        selected: false,
      },
      position: {
        x: -1435.9622619870402,
        y: -478.53028895293335,
      },
      selected: false,
    },
    {
      data: {
        id: "346",
        shared_name: "DNAmethylation",
        exposure_attr: "both",
        centrality: 0.0200086058519793,
        outcome_attr: "both",
        name: "DNAmethylation",
        SUID: 346,
        selected: false,
      },
      position: {
        x: -167.4643578644027,
        y: -537.0625786343625,
      },
      selected: false,
    },
    {
      data: {
        id: "344",
        shared_name: "blood pressure",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "blood pressure",
        SUID: 344,
        selected: false,
      },
      position: {
        x: -938.7960436022056,
        y: -1367.871316410929,
      },
      selected: false,
    },
    {
      data: {
        id: "342",
        shared_name: "incident cancer",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "incident cancer",
        SUID: 342,
        selected: false,
      },
      position: {
        x: 1216.8819443488067,
        y: -1456.1089566201767,
      },
      selected: false,
    },
    {
      data: {
        id: "340",
        shared_name: "leukocyte telomere length",
        exposure_attr: "both",
        centrality: 5.020080321285e-4,
        outcome_attr: "both",
        name: "leukocyte telomere length",
        SUID: 340,
        selected: false,
      },
      position: {
        x: 280.68590296003794,
        y: -1021.0823463716155,
      },
      selected: false,
    },
    {
      data: {
        id: "338",
        shared_name: "lung function",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "lung function",
        SUID: 338,
        selected: false,
      },
      position: {
        x: 460.6907930464267,
        y: 79.54621899683282,
      },
      selected: false,
    },
    {
      data: {
        id: "336",
        shared_name: "mitochondrial DNA",
        exposure_attr: "both",
        centrality: 2.151462994836e-4,
        outcome_attr: "both",
        name: "mitochondrial DNA",
        SUID: 336,
        selected: false,
      },
      position: {
        x: 39.07859327982448,
        y: -1202.5771622559191,
      },
      selected: false,
    },
    {
      data: {
        id: "334",
        shared_name: "mortality",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "mortality",
        SUID: 334,
        selected: false,
      },
      position: {
        x: -2012.145776118904,
        y: -64.03190322712102,
      },
      selected: false,
    },
    {
      data: {
        id: "332",
        shared_name: "air pollution",
        exposure_attr: "both",
        centrality: 0.0040160642570281,
        outcome_attr: "both",
        name: "air pollution",
        SUID: 332,
        selected: false,
      },
      position: {
        x: -1153.9665220040808,
        y: -852.7361829091049,
      },
      selected: false,
    },
    {
      data: {
        id: "330",
        shared_name: "arterial stiffness",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "arterial stiffness",
        SUID: 330,
        selected: false,
      },
      position: {
        x: -2132.077880612803,
        y: -1529.0694693881073,
      },
      selected: false,
    },
    {
      data: {
        id: "328",
        shared_name: "blood urea nitrogen",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "blood urea nitrogen",
        SUID: 328,
        selected: false,
      },
      position: {
        x: -1520.8168207312826,
        y: -1290.8652048744132,
      },
      selected: false,
    },
    {
      data: {
        id: "326",
        shared_name: "cognitive function",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "cognitive function",
        SUID: 326,
        selected: false,
      },
      position: {
        x: -140.08298306602902,
        y: -1721.7395387792715,
      },
      selected: false,
    },
    {
      data: {
        id: "324",
        shared_name: "electrocardiogram",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "electrocardiogram",
        SUID: 324,
        selected: false,
      },
      position: {
        x: 486.0784277315518,
        y: -1863.6390716853602,
      },
      selected: false,
    },
    {
      data: {
        id: "322",
        shared_name: "fasting blood glucose",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "fasting blood glucose",
        SUID: 322,
        selected: false,
      },
      position: {
        x: -1778.3904291551505,
        y: -1432.6000762221922,
      },
      selected: false,
    },
    {
      data: {
        id: "320",
        shared_name: "glomerular filtration rate",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "glomerular filtration rate",
        SUID: 320,
        selected: false,
      },
      position: {
        x: -2365.5893387007995,
        y: -749.6471595620158,
      },
      selected: false,
    },
    {
      data: {
        id: "318",
        shared_name: "hemoglobin concentration",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "hemoglobin concentration",
        SUID: 318,
        selected: false,
      },
      position: {
        x: -2302.252474984465,
        y: -998.3384857153515,
      },
      selected: false,
    },
    {
      data: {
        id: "316",
        shared_name: "incident abnormal cardiac conductivity",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "incident abnormal cardiac conductivity",
        SUID: 316,
        selected: false,
      },
      position: {
        x: 1294.7761223884104,
        y: -977.0666480254646,
      },
      selected: false,
    },
    {
      data: {
        id: "314",
        shared_name: "incident chronic kidney disease",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "incident chronic kidney disease",
        SUID: 314,
        selected: false,
      },
      position: {
        x: -1965.0805255746711,
        y: -1151.360358813962,
      },
      selected: false,
    },
    {
      data: {
        id: "312",
        shared_name: "incident metabolic syndrome",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "incident metabolic syndrome",
        SUID: 312,
        selected: false,
      },
      position: {
        x: -664.2744174137874,
        y: -1565.8184003276522,
      },
      selected: false,
    },
    {
      data: {
        id: "310",
        shared_name: "inflammation biomarkers",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "inflammation biomarkers",
        SUID: 310,
        selected: false,
      },
      position: {
        x: 1312.3796760242822,
        y: -417.6002329075699,
      },
      selected: false,
    },
    {
      data: {
        id: "308",
        shared_name: "intima-media thickness of the common carotid artery",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "intima-media thickness of the common carotid artery",
        SUID: 308,
        selected: false,
      },
      position: {
        x: -2255.2044840489853,
        y: -1343.6784835760518,
      },
      selected: false,
    },
    {
      data: {
        id: "306",
        shared_name: "intraocular pressure",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "intraocular pressure",
        SUID: 306,
        selected: false,
      },
      position: {
        x: -2110.803308235325,
        y: -866.0266911743238,
      },
      selected: false,
    },
    {
      data: {
        id: "304",
        shared_name: "leukocyte distribution",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "leukocyte distribution",
        SUID: 304,
        selected: false,
      },
      position: {
        x: -1266.2875384679091,
        y: -1650.1364726049133,
      },
      selected: false,
    },
    {
      data: {
        id: "302",
        shared_name: "lipid profile",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "lipid profile",
        SUID: 302,
        selected: false,
      },
      position: {
        x: 526.5839353121848,
        y: -1338.4038265629636,
      },
      selected: false,
    },
    {
      data: {
        id: "300",
        shared_name: "metabolic syndrome components",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "metabolic syndrome components",
        SUID: 300,
        selected: false,
      },
      position: {
        x: -473.12826266868285,
        y: -1784.2320718263659,
      },
      selected: false,
    },
    {
      data: {
        id: "298",
        shared_name: "metabolites",
        exposure_attr: "both",
        centrality: 5.020080321285e-4,
        outcome_attr: "both",
        name: "metabolites",
        SUID: 298,
        selected: false,
      },
      position: {
        x: -473.6940495681474,
        y: -745.752422832163,
      },
      selected: false,
    },
    {
      data: {
        id: "296",
        shared_name: "microRNA",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "microRNA",
        SUID: 296,
        selected: false,
      },
      position: {
        x: -1123.1783989706187,
        y: -1444.6022460443162,
      },
      selected: false,
    },
    {
      data: {
        id: "294",
        shared_name: "oxidative DNA damage",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "oxidative DNA damage",
        SUID: 294,
        selected: false,
      },
      position: {
        x: -2430.3499888535607,
        y: -1139.7490657121978,
      },
      selected: false,
    },
    {
      data: {
        id: "292",
        shared_name: "perceived stress",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "perceived stress",
        SUID: 292,
        selected: false,
      },
      position: {
        x: -1418.5739236926988,
        y: -1478.343019770644,
      },
      selected: false,
    },
    {
      data: {
        id: "290",
        shared_name: "serum uric acid",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "serum uric acid",
        SUID: 290,
        selected: false,
      },
      position: {
        x: -2194.9630491921257,
        y: -535.8583520306906,
      },
      selected: false,
    },
    {
      data: {
        id: "288",
        shared_name: "alcohol",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "alcohol",
        SUID: 288,
        selected: false,
      },
      position: {
        x: -1745.80681524216,
        y: -578.2352386242768,
      },
      selected: false,
    },
    {
      data: {
        id: "286",
        shared_name: "allergic phenotypes",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "allergic phenotypes",
        SUID: 286,
        selected: false,
      },
      position: {
        x: -677.8880186099162,
        y: -227.74573679800991,
      },
      selected: false,
    },
    {
      data: {
        id: "284",
        shared_name: "anxiety",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "anxiety",
        SUID: 284,
        selected: false,
      },
      position: {
        x: -303.93624633730644,
        y: -33.25363453833049,
      },
      selected: false,
    },
    {
      data: {
        id: "282",
        shared_name: "asthma",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "asthma",
        SUID: 282,
        selected: false,
      },
      position: {
        x: -493.0653342151922,
        y: -116.6416326194031,
      },
      selected: false,
    },
    {
      data: {
        id: "280",
        shared_name: "biological aging",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "biological aging",
        SUID: 280,
        selected: false,
      },
      position: {
        x: -71.9343052575552,
        y: -1381.8861195747675,
      },
      selected: false,
    },
    {
      data: {
        id: "278",
        shared_name: "blood lead",
        exposure_attr: "both",
        centrality: 6.454388984509e-4,
        outcome_attr: "both",
        name: "blood lead",
        SUID: 278,
        selected: false,
      },
      position: {
        x: 1040.7354048565403,
        y: -299.5094469843957,
      },
      selected: false,
    },
    {
      data: {
        id: "276",
        shared_name: "plasma homocysteine",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "plasma homocysteine",
        SUID: 276,
        selected: false,
      },
      position: {
        x: 1588.3873241614274,
        y: 260.414738209402,
      },
      selected: false,
    },
    {
      data: {
        id: "274",
        shared_name: "resistant hypertension",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "resistant hypertension",
        SUID: 274,
        selected: false,
      },
      position: {
        x: 1763.872282051133,
        y: -68.2178174068963,
      },
      selected: false,
    },
    {
      data: {
        id: "272",
        shared_name: "tremor",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "tremor",
        SUID: 272,
        selected: false,
      },
      position: {
        x: 1753.4401813960299,
        y: 119.34861483642943,
      },
      selected: false,
    },
    {
      data: {
        id: "270",
        shared_name: "urinary metals",
        exposure_attr: "both",
        centrality: 5.020080321285e-4,
        outcome_attr: "both",
        name: "urinary metals",
        SUID: 270,
        selected: false,
      },
      position: {
        x: 648.2777104026247,
        y: -104.89576890563283,
      },
      selected: false,
    },
    {
      data: {
        id: "268",
        shared_name: "bone lead",
        exposure_attr: "both",
        centrality: 0.0043746414228341,
        outcome_attr: "both",
        name: "bone lead",
        SUID: 268,
        selected: false,
      },
      position: {
        x: 1110.682221612838,
        y: -46.29834049390434,
      },
      selected: false,
    },
    {
      data: {
        id: "266",
        shared_name: "cardiovascular disease",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "cardiovascular disease",
        SUID: 266,
        selected: false,
      },
      position: {
        x: 1626.546656423647,
        y: -333.399767147221,
      },
      selected: false,
    },
    {
      data: {
        id: "264",
        shared_name: "fine motor function",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "fine motor function",
        SUID: 264,
        selected: false,
      },
      position: {
        x: 1115.2033599134122,
        y: 321.28503656291264,
      },
      selected: false,
    },
    {
      data: {
        id: "262",
        shared_name: "glaucoma",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "glaucoma",
        SUID: 262,
        selected: false,
      },
      position: {
        x: 811.7746597665675,
        y: 251.88757578970024,
      },
      selected: false,
    },
    {
      data: {
        id: "260",
        shared_name: "neural plasticity",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "neural plasticity",
        SUID: 260,
        selected: false,
      },
      position: {
        x: 1266.1265433891747,
        y: 468.2701534467601,
      },
      selected: false,
    },
    {
      data: {
        id: "258",
        shared_name: "olfactory recognition",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "olfactory recognition",
        SUID: 258,
        selected: false,
      },
      position: {
        x: 507.69056918883507,
        y: 318.5684251719367,
      },
      selected: false,
    },
    {
      data: {
        id: "256",
        shared_name: "depression",
        exposure_attr: "both",
        centrality: 0.0031554790590935,
        outcome_attr: "both",
        name: "depression",
        SUID: 256,
        selected: false,
      },
      position: {
        x: -908.1126534274459,
        y: -597.4155631028441,
      },
      selected: false,
    },
    {
      data: {
        id: "254",
        shared_name: "co-occurrence of affect",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "co-occurrence of affect",
        SUID: 254,
        selected: false,
      },
      position: {
        x: -977.1173713764119,
        y: 222.8461466490523,
      },
      selected: false,
    },
    {
      data: {
        id: "252",
        shared_name: "reactivity to health stressors",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "reactivity to health stressors",
        SUID: 252,
        selected: false,
      },
      position: {
        x: -992.3468039427057,
        y: 495.6985327494583,
      },
      selected: false,
    },
    {
      data: {
        id: "250",
        shared_name: "diabetes",
        exposure_attr: "both",
        centrality: 1.434308663224e-4,
        outcome_attr: "both",
        name: "diabetes",
        SUID: 250,
        selected: false,
      },
      position: {
        x: 132.1115563778392,
        y: -1883.2467064423672,
      },
      selected: false,
    },
    {
      data: {
        id: "248",
        shared_name: "diet",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "diet",
        SUID: 248,
        selected: false,
      },
      position: {
        x: 601.0753471581271,
        y: -439.6872229093595,
      },
      selected: false,
    },
    {
      data: {
        id: "246",
        shared_name: "periodontal disease progression",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "periodontal disease progression",
        SUID: 246,
        selected: false,
      },
      position: {
        x: 1575.8844066786153,
        y: -577.6616179355639,
      },
      selected: false,
    },
    {
      data: {
        id: "244",
        shared_name: "drug use",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "drug use",
        SUID: 244,
        selected: false,
      },
      position: {
        x: -672.9754239940568,
        y: -53.60653131473808,
      },
      selected: false,
    },
    {
      data: {
        id: "242",
        shared_name: "emotional reactivity",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "emotional reactivity",
        SUID: 242,
        selected: false,
      },
      position: {
        x: -1621.0398332461175,
        y: 48.94944943362471,
      },
      selected: false,
    },
    {
      data: {
        id: "240",
        shared_name: "family",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "family",
        SUID: 240,
        selected: false,
      },
      position: {
        x: -1809.5607622344842,
        y: 254.768243160932,
      },
      selected: false,
    },
    {
      data: {
        id: "238",
        shared_name: "psychological well-being",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "psychological well-being",
        SUID: 238,
        selected: false,
      },
      position: {
        x: -1855.737744204101,
        y: 515.3024220102025,
      },
      selected: false,
    },
    {
      data: {
        id: "236",
        shared_name: "genes",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "genes",
        SUID: 236,
        selected: false,
      },
      position: {
        x: 181.23981869879526,
        y: -1636.838238672011,
      },
      selected: false,
    },
    {
      data: {
        id: "234",
        shared_name: "toenail metals",
        exposure_attr: "both",
        centrality: 0.0011474469305794,
        outcome_attr: "both",
        name: "toenail metals",
        SUID: 234,
        selected: false,
      },
      position: {
        x: -470.1561234940578,
        y: -1424.706331725583,
      },
      selected: false,
    },
    {
      data: {
        id: "232",
        shared_name: "happiness",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "happiness",
        SUID: 232,
        selected: false,
      },
      position: {
        x: -64.6466940406197,
        y: 1.2286617325462137,
      },
      selected: false,
    },
    {
      data: {
        id: "230",
        shared_name: "hassles and uplifts",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "hassles and uplifts",
        SUID: 230,
        selected: false,
      },
      position: {
        x: -2091.214872734423,
        y: 349.29801638856486,
      },
      selected: false,
    },
    {
      data: {
        id: "228",
        shared_name: "hormone",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "hormone",
        SUID: 228,
        selected: false,
      },
      position: {
        x: 2006.9118931686824,
        y: -785.4628918299641,
      },
      selected: false,
    },
    {
      data: {
        id: "226",
        shared_name: "hostility",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "hostility",
        SUID: 226,
        selected: false,
      },
      position: {
        x: -499.24208164393883,
        y: 63.245176899878786,
      },
      selected: false,
    },
    {
      data: {
        id: "224",
        shared_name: "hypertension",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "hypertension",
        SUID: 224,
        selected: false,
      },
      position: {
        x: -150.46532231755555,
        y: -2033.4249757200014,
      },
      selected: false,
    },
    {
      data: {
        id: "222",
        shared_name: "life satisfaction",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "life satisfaction",
        SUID: 222,
        selected: false,
      },
      position: {
        x: -188.88427935722052,
        y: 125.93651753463956,
      },
      selected: false,
    },
    {
      data: {
        id: "220",
        shared_name: "metabolic syndrome component",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "metabolic syndrome component",
        SUID: 220,
        selected: false,
      },
      position: {
        x: 1606.444556300711,
        y: -837.3881599938719,
      },
      selected: false,
    },
    {
      data: {
        id: "218",
        shared_name: "tooth loss",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "tooth loss",
        SUID: 218,
        selected: false,
      },
      position: {
        x: 1719.9259510914271,
        y: -1135.3900143578855,
      },
      selected: false,
    },
    {
      data: {
        id: "216",
        shared_name: "occupation",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "occupation",
        SUID: 216,
        selected: false,
      },
      position: {
        x: 899.6993288887036,
        y: 407.99396288577515,
      },
      selected: false,
    },
    {
      data: {
        id: "214",
        shared_name: "openness to experiences",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "openness to experiences",
        SUID: 214,
        selected: false,
      },
      position: {
        x: -2473.4645579914104,
        y: 271.207396018603,
      },
      selected: false,
    },
    {
      data: {
        id: "212",
        shared_name: "optimism",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "optimism",
        SUID: 212,
        selected: false,
      },
      position: {
        x: 590.9775382322856,
        y: -670.797328839876,
      },
      selected: false,
    },
    {
      data: {
        id: "210",
        shared_name: "endothelial dysfunction markers",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "endothelial dysfunction markers",
        SUID: 210,
        selected: false,
      },
      position: {
        x: 1140.8392328471932,
        y: -795.1729539656621,
      },
      selected: false,
    },
    {
      data: {
        id: "208",
        shared_name: "leukocyte telomere length change rate",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "leukocyte telomere length change rate",
        SUID: 208,
        selected: false,
      },
      position: {
        x: 1068.4445050102552,
        y: -1145.1536612975174,
      },
      selected: false,
    },
    {
      data: {
        id: "206",
        shared_name: "pessimism",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "pessimism",
        SUID: 206,
        selected: false,
      },
      position: {
        x: 813.2384580460304,
        y: -1389.422507458804,
      },
      selected: false,
    },
    {
      data: {
        id: "204",
        shared_name: "psychosocial stressors",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "psychosocial stressors",
        SUID: 204,
        selected: false,
      },
      position: {
        x: -2379.374280907019,
        y: 438.87867818388037,
      },
      selected: false,
    },
    {
      data: {
        id: "202",
        shared_name: "relative humidity",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "relative humidity",
        SUID: 202,
        selected: false,
      },
      position: {
        x: 202.09901958389668,
        y: 240.19163940359724,
      },
      selected: false,
    },
    {
      data: {
        id: "200",
        shared_name: "road proximity",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "road proximity",
        SUID: 200,
        selected: false,
      },
      position: {
        x: -2037.8118666052105,
        y: -678.5546830624938,
      },
      selected: false,
    },
    {
      data: {
        id: "198",
        shared_name: "self-regulation",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "self-regulation",
        SUID: 198,
        selected: false,
      },
      position: {
        x: 1962.1345570688409,
        y: -207.93984520583098,
      },
      selected: false,
    },
    {
      data: {
        id: "196",
        shared_name: "sleep",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "sleep",
        SUID: 196,
        selected: false,
      },
      position: {
        x: -1368.2247311552642,
        y: 222.6050481110185,
      },
      selected: false,
    },
    {
      data: {
        id: "194",
        shared_name: "alzheimer disease biomarkers",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "alzheimer disease biomarkers",
        SUID: 194,
        selected: false,
      },
      position: {
        x: -1374.2329021997527,
        y: 455.5773565290034,
      },
      selected: false,
    },
    {
      data: {
        id: "192",
        shared_name: "smoking",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "smoking",
        SUID: 192,
        selected: false,
      },
      position: {
        x: -1012.2365816164527,
        y: -385.7933315062228,
      },
      selected: false,
    },
    {
      data: {
        id: "190",
        shared_name: "solar and geomagnetic activity",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "solar and geomagnetic activity",
        SUID: 190,
        selected: false,
      },
      position: {
        x: -915.8072365016714,
        y: -1708.8891777296951,
      },
      selected: false,
    },
    {
      data: {
        id: "188",
        shared_name: "white blood cell counts",
        exposure_attr: "",
        centrality: 0.0,
        outcome_attr: "outcomes",
        name: "white blood cell counts",
        SUID: 188,
        selected: false,
      },
      position: {
        x: -987.9864582446475,
        y: -2008.6682134990037,
      },
      selected: false,
    },
    {
      data: {
        id: "186",
        shared_name: "stressful life events",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "stressful life events",
        SUID: 186,
        selected: false,
      },
      position: {
        x: -2495.415777215163,
        y: 65.83390148949431,
      },
      selected: false,
    },
    {
      data: {
        id: "184",
        shared_name: "temperature",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "temperature",
        SUID: 184,
        selected: false,
      },
      position: {
        x: -212.53818949416694,
        y: -944.1169567947027,
      },
      selected: false,
    },
    {
      data: {
        id: "182",
        shared_name: "tocopherol levels",
        exposure_attr: "exposures",
        centrality: 0.0,
        outcome_attr: "",
        name: "tocopherol levels",
        SUID: 182,
        selected: false,
      },
      position: {
        x: 368.17386954848973,
        y: -1477.4646775753495,
      },
      selected: false,
    },
  ],
  edges: [
    {
      data: {
        id: "616",
        source: "350",
        target: "348",
        shared_name: "BMI (interacts with) cholesterol level",
        shared_interaction: "interacts with",
        name: "BMI (interacts with) cholesterol level",
        interaction: "interacts with",
        edge_id: 1,
        SUID: 616,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "614",
        source: "348",
        target: "256",
        shared_name: "cholesterol level (interacts with) depression",
        shared_interaction: "interacts with",
        name: "cholesterol level (interacts with) depression",
        interaction: "interacts with",
        edge_id: 63,
        SUID: 614,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "612",
        source: "348",
        target: "334",
        shared_name: "cholesterol level (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "cholesterol level (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 64,
        SUID: 612,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "610",
        source: "346",
        target: "344",
        shared_name: "DNAmethylation (interacts with) blood pressure",
        shared_interaction: "interacts with",
        name: "DNAmethylation (interacts with) blood pressure",
        interaction: "interacts with",
        edge_id: 2,
        SUID: 610,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "608",
        source: "346",
        target: "342",
        shared_name: "DNAmethylation (interacts with) incident cancer",
        shared_interaction: "interacts with",
        name: "DNAmethylation (interacts with) incident cancer",
        interaction: "interacts with",
        edge_id: 3,
        SUID: 608,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "606",
        source: "346",
        target: "340",
        shared_name:
          "DNAmethylation (interacts with) leukocyte telomere length",
        shared_interaction: "interacts with",
        name: "DNAmethylation (interacts with) leukocyte telomere length",
        interaction: "interacts with",
        edge_id: 4,
        SUID: 606,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "604",
        source: "346",
        target: "338",
        shared_name: "DNAmethylation (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "DNAmethylation (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 5,
        SUID: 604,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "602",
        source: "346",
        target: "336",
        shared_name: "DNAmethylation (interacts with) mitochondrial DNA",
        shared_interaction: "interacts with",
        name: "DNAmethylation (interacts with) mitochondrial DNA",
        interaction: "interacts with",
        edge_id: 6,
        SUID: 602,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "600",
        source: "346",
        target: "334",
        shared_name: "DNAmethylation (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "DNAmethylation (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 7,
        SUID: 600,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "598",
        source: "340",
        target: "342",
        shared_name:
          "leukocyte telomere length (interacts with) incident cancer",
        shared_interaction: "interacts with",
        name: "leukocyte telomere length (interacts with) incident cancer",
        interaction: "interacts with",
        edge_id: 88,
        SUID: 598,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "596",
        source: "340",
        target: "338",
        shared_name: "leukocyte telomere length (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "leukocyte telomere length (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 89,
        SUID: 596,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "594",
        source: "336",
        target: "346",
        shared_name: "mitochondrial DNA (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "mitochondrial DNA (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 94,
        SUID: 594,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "592",
        source: "336",
        target: "340",
        shared_name:
          "mitochondrial DNA (interacts with) leukocyte telomere length",
        shared_interaction: "interacts with",
        name: "mitochondrial DNA (interacts with) leukocyte telomere length",
        interaction: "interacts with",
        edge_id: 95,
        SUID: 592,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "590",
        source: "336",
        target: "338",
        shared_name: "mitochondrial DNA (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "mitochondrial DNA (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 96,
        SUID: 590,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "588",
        source: "332",
        target: "346",
        shared_name: "air pollution (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 8,
        SUID: 588,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "586",
        source: "332",
        target: "330",
        shared_name: "air pollution (interacts with) arterial stiffness",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) arterial stiffness",
        interaction: "interacts with",
        edge_id: 9,
        SUID: 586,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "584",
        source: "332",
        target: "344",
        shared_name: "air pollution (interacts with) blood pressure",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) blood pressure",
        interaction: "interacts with",
        edge_id: 10,
        SUID: 584,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "582",
        source: "332",
        target: "328",
        shared_name: "air pollution (interacts with) blood urea nitrogen",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) blood urea nitrogen",
        interaction: "interacts with",
        edge_id: 11,
        SUID: 582,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "580",
        source: "332",
        target: "326",
        shared_name: "air pollution (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 12,
        SUID: 580,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "578",
        source: "332",
        target: "324",
        shared_name: "air pollution (interacts with) electrocardiogram",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) electrocardiogram",
        interaction: "interacts with",
        edge_id: 13,
        SUID: 578,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "576",
        source: "332",
        target: "322",
        shared_name: "air pollution (interacts with) fasting blood glucose",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) fasting blood glucose",
        interaction: "interacts with",
        edge_id: 14,
        SUID: 576,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "574",
        source: "332",
        target: "320",
        shared_name:
          "air pollution (interacts with) glomerular filtration rate",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) glomerular filtration rate",
        interaction: "interacts with",
        edge_id: 15,
        SUID: 574,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "572",
        source: "332",
        target: "318",
        shared_name: "air pollution (interacts with) hemoglobin concentration",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) hemoglobin concentration",
        interaction: "interacts with",
        edge_id: 16,
        SUID: 572,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "570",
        source: "332",
        target: "316",
        shared_name:
          "air pollution (interacts with) incident abnormal cardiac conductivity",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) incident abnormal cardiac conductivity",
        interaction: "interacts with",
        edge_id: 17,
        SUID: 570,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "568",
        source: "332",
        target: "314",
        shared_name:
          "air pollution (interacts with) incident chronic kidney disease",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) incident chronic kidney disease",
        interaction: "interacts with",
        edge_id: 18,
        SUID: 568,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "566",
        source: "332",
        target: "312",
        shared_name:
          "air pollution (interacts with) incident metabolic syndrome",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) incident metabolic syndrome",
        interaction: "interacts with",
        edge_id: 19,
        SUID: 566,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "564",
        source: "332",
        target: "310",
        shared_name: "air pollution (interacts with) inflammation biomarkers",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) inflammation biomarkers",
        interaction: "interacts with",
        edge_id: 20,
        SUID: 564,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "562",
        source: "332",
        target: "308",
        shared_name:
          "air pollution (interacts with) intima-media thickness of the common carotid artery",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) intima-media thickness of the common carotid artery",
        interaction: "interacts with",
        edge_id: 21,
        SUID: 562,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "560",
        source: "332",
        target: "306",
        shared_name: "air pollution (interacts with) intraocular pressure",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) intraocular pressure",
        interaction: "interacts with",
        edge_id: 22,
        SUID: 560,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "558",
        source: "332",
        target: "304",
        shared_name: "air pollution (interacts with) leukocyte distribution",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) leukocyte distribution",
        interaction: "interacts with",
        edge_id: 23,
        SUID: 558,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "556",
        source: "332",
        target: "302",
        shared_name: "air pollution (interacts with) lipid profile",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) lipid profile",
        interaction: "interacts with",
        edge_id: 24,
        SUID: 556,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "554",
        source: "332",
        target: "338",
        shared_name: "air pollution (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 25,
        SUID: 554,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "552",
        source: "332",
        target: "300",
        shared_name:
          "air pollution (interacts with) metabolic syndrome components",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) metabolic syndrome components",
        interaction: "interacts with",
        edge_id: 26,
        SUID: 552,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "550",
        source: "332",
        target: "298",
        shared_name: "air pollution (interacts with) metabolites",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) metabolites",
        interaction: "interacts with",
        edge_id: 27,
        SUID: 550,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "548",
        source: "332",
        target: "296",
        shared_name: "air pollution (interacts with) microRNA",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) microRNA",
        interaction: "interacts with",
        edge_id: 28,
        SUID: 548,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "546",
        source: "332",
        target: "336",
        shared_name: "air pollution (interacts with) mitochondrial DNA",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) mitochondrial DNA",
        interaction: "interacts with",
        edge_id: 29,
        SUID: 546,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "544",
        source: "332",
        target: "294",
        shared_name: "air pollution (interacts with) oxidative DNA damage",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) oxidative DNA damage",
        interaction: "interacts with",
        edge_id: 30,
        SUID: 544,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "542",
        source: "332",
        target: "292",
        shared_name: "air pollution (interacts with) perceived stress",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) perceived stress",
        interaction: "interacts with",
        edge_id: 31,
        SUID: 542,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "540",
        source: "332",
        target: "290",
        shared_name: "air pollution (interacts with) serum uric acid",
        shared_interaction: "interacts with",
        name: "air pollution (interacts with) serum uric acid",
        interaction: "interacts with",
        edge_id: 32,
        SUID: 540,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "538",
        source: "298",
        target: "346",
        shared_name: "metabolites (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "metabolites (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 93,
        SUID: 538,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "536",
        source: "288",
        target: "348",
        shared_name: "alcohol (interacts with) cholesterol level",
        shared_interaction: "interacts with",
        name: "alcohol (interacts with) cholesterol level",
        interaction: "interacts with",
        edge_id: 33,
        SUID: 536,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "534",
        source: "286",
        target: "346",
        shared_name: "allergic phenotypes (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "allergic phenotypes (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 34,
        SUID: 534,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "532",
        source: "284",
        target: "346",
        shared_name: "anxiety (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "anxiety (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 35,
        SUID: 532,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "530",
        source: "282",
        target: "346",
        shared_name: "asthma (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "asthma (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 36,
        SUID: 530,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "528",
        source: "280",
        target: "346",
        shared_name: "biological aging (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "biological aging (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 37,
        SUID: 528,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "526",
        source: "280",
        target: "326",
        shared_name: "biological aging (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "biological aging (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 38,
        SUID: 526,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "524",
        source: "278",
        target: "324",
        shared_name: "blood lead (interacts with) electrocardiogram",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) electrocardiogram",
        interaction: "interacts with",
        edge_id: 39,
        SUID: 524,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "522",
        source: "278",
        target: "316",
        shared_name:
          "blood lead (interacts with) incident abnormal cardiac conductivity",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) incident abnormal cardiac conductivity",
        interaction: "interacts with",
        edge_id: 40,
        SUID: 522,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "520",
        source: "278",
        target: "310",
        shared_name: "blood lead (interacts with) inflammation biomarkers",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) inflammation biomarkers",
        interaction: "interacts with",
        edge_id: 41,
        SUID: 520,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "518",
        source: "278",
        target: "302",
        shared_name: "blood lead (interacts with) lipid profile",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) lipid profile",
        interaction: "interacts with",
        edge_id: 42,
        SUID: 518,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "516",
        source: "278",
        target: "298",
        shared_name: "blood lead (interacts with) metabolites",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) metabolites",
        interaction: "interacts with",
        edge_id: 43,
        SUID: 516,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "514",
        source: "278",
        target: "276",
        shared_name: "blood lead (interacts with) plasma homocysteine",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) plasma homocysteine",
        interaction: "interacts with",
        edge_id: 44,
        SUID: 514,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "512",
        source: "278",
        target: "274",
        shared_name: "blood lead (interacts with) resistant hypertension",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) resistant hypertension",
        interaction: "interacts with",
        edge_id: 45,
        SUID: 512,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "510",
        source: "278",
        target: "272",
        shared_name: "blood lead (interacts with) tremor",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) tremor",
        interaction: "interacts with",
        edge_id: 46,
        SUID: 510,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "508",
        source: "278",
        target: "270",
        shared_name: "blood lead (interacts with) urinary metals",
        shared_interaction: "interacts with",
        name: "blood lead (interacts with) urinary metals",
        interaction: "interacts with",
        edge_id: 47,
        SUID: 508,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "506",
        source: "270",
        target: "346",
        shared_name: "urinary metals (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "urinary metals (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 130,
        SUID: 506,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "504",
        source: "268",
        target: "346",
        shared_name: "bone lead (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 48,
        SUID: 504,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "502",
        source: "268",
        target: "266",
        shared_name: "bone lead (interacts with) cardiovascular disease",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) cardiovascular disease",
        interaction: "interacts with",
        edge_id: 49,
        SUID: 502,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "500",
        source: "268",
        target: "326",
        shared_name: "bone lead (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 50,
        SUID: 500,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "498",
        source: "268",
        target: "324",
        shared_name: "bone lead (interacts with) electrocardiogram",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) electrocardiogram",
        interaction: "interacts with",
        edge_id: 51,
        SUID: 498,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "496",
        source: "268",
        target: "264",
        shared_name: "bone lead (interacts with) fine motor function",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) fine motor function",
        interaction: "interacts with",
        edge_id: 52,
        SUID: 496,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "494",
        source: "268",
        target: "262",
        shared_name: "bone lead (interacts with) glaucoma",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) glaucoma",
        interaction: "interacts with",
        edge_id: 53,
        SUID: 494,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "492",
        source: "268",
        target: "316",
        shared_name:
          "bone lead (interacts with) incident abnormal cardiac conductivity",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) incident abnormal cardiac conductivity",
        interaction: "interacts with",
        edge_id: 54,
        SUID: 492,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "490",
        source: "268",
        target: "310",
        shared_name: "bone lead (interacts with) inflammation biomarkers",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) inflammation biomarkers",
        interaction: "interacts with",
        edge_id: 55,
        SUID: 490,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "488",
        source: "268",
        target: "302",
        shared_name: "bone lead (interacts with) lipid profile",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) lipid profile",
        interaction: "interacts with",
        edge_id: 56,
        SUID: 488,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "486",
        source: "268",
        target: "260",
        shared_name: "bone lead (interacts with) neural plasticity",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) neural plasticity",
        interaction: "interacts with",
        edge_id: 57,
        SUID: 486,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "484",
        source: "268",
        target: "258",
        shared_name: "bone lead (interacts with) olfactory recognition",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) olfactory recognition",
        interaction: "interacts with",
        edge_id: 58,
        SUID: 484,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "482",
        source: "268",
        target: "276",
        shared_name: "bone lead (interacts with) plasma homocysteine",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) plasma homocysteine",
        interaction: "interacts with",
        edge_id: 59,
        SUID: 482,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "480",
        source: "268",
        target: "274",
        shared_name: "bone lead (interacts with) resistant hypertension",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) resistant hypertension",
        interaction: "interacts with",
        edge_id: 60,
        SUID: 480,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "478",
        source: "268",
        target: "272",
        shared_name: "bone lead (interacts with) tremor",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) tremor",
        interaction: "interacts with",
        edge_id: 61,
        SUID: 478,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "476",
        source: "268",
        target: "270",
        shared_name: "bone lead (interacts with) urinary metals",
        shared_interaction: "interacts with",
        name: "bone lead (interacts with) urinary metals",
        interaction: "interacts with",
        edge_id: 62,
        SUID: 476,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "474",
        source: "256",
        target: "346",
        shared_name: "depression (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "depression (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 66,
        SUID: 474,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "472",
        source: "256",
        target: "326",
        shared_name: "depression (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "depression (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 67,
        SUID: 472,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "470",
        source: "254",
        target: "252",
        shared_name:
          "co-occurrence of affect (interacts with) reactivity to health stressors",
        shared_interaction: "interacts with",
        name: "co-occurrence of affect (interacts with) reactivity to health stressors",
        interaction: "interacts with",
        edge_id: 65,
        SUID: 470,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "468",
        source: "250",
        target: "326",
        shared_name: "diabetes (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "diabetes (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 68,
        SUID: 468,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "466",
        source: "248",
        target: "346",
        shared_name: "diet (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "diet (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 69,
        SUID: 466,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "464",
        source: "248",
        target: "278",
        shared_name: "diet (interacts with) blood lead",
        shared_interaction: "interacts with",
        name: "diet (interacts with) blood lead",
        interaction: "interacts with",
        edge_id: 70,
        SUID: 464,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "462",
        source: "248",
        target: "268",
        shared_name: "diet (interacts with) bone lead",
        shared_interaction: "interacts with",
        name: "diet (interacts with) bone lead",
        interaction: "interacts with",
        edge_id: 71,
        SUID: 462,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "460",
        source: "248",
        target: "310",
        shared_name: "diet (interacts with) inflammation biomarkers",
        shared_interaction: "interacts with",
        name: "diet (interacts with) inflammation biomarkers",
        interaction: "interacts with",
        edge_id: 72,
        SUID: 460,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "458",
        source: "248",
        target: "338",
        shared_name: "diet (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "diet (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 73,
        SUID: 458,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "456",
        source: "248",
        target: "246",
        shared_name: "diet (interacts with) periodontal disease progression",
        shared_interaction: "interacts with",
        name: "diet (interacts with) periodontal disease progression",
        interaction: "interacts with",
        edge_id: 74,
        SUID: 456,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "454",
        source: "244",
        target: "346",
        shared_name: "drug use (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "drug use (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 75,
        SUID: 454,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "452",
        source: "242",
        target: "334",
        shared_name: "emotional reactivity (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "emotional reactivity (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 76,
        SUID: 452,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "450",
        source: "240",
        target: "334",
        shared_name: "family (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "family (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 77,
        SUID: 450,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "448",
        source: "240",
        target: "238",
        shared_name: "family (interacts with) psychological well-being",
        shared_interaction: "interacts with",
        name: "family (interacts with) psychological well-being",
        interaction: "interacts with",
        edge_id: 78,
        SUID: 448,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "446",
        source: "236",
        target: "266",
        shared_name: "genes (interacts with) cardiovascular disease",
        shared_interaction: "interacts with",
        name: "genes (interacts with) cardiovascular disease",
        interaction: "interacts with",
        edge_id: 79,
        SUID: 446,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "444",
        source: "236",
        target: "326",
        shared_name: "genes (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "genes (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 80,
        SUID: 444,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "442",
        source: "236",
        target: "234",
        shared_name: "genes (interacts with) toenail metals",
        shared_interaction: "interacts with",
        name: "genes (interacts with) toenail metals",
        interaction: "interacts with",
        edge_id: 81,
        SUID: 442,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "440",
        source: "234",
        target: "346",
        shared_name: "toenail metals (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "toenail metals (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 127,
        SUID: 440,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "438",
        source: "234",
        target: "344",
        shared_name: "toenail metals (interacts with) blood pressure",
        shared_interaction: "interacts with",
        name: "toenail metals (interacts with) blood pressure",
        interaction: "interacts with",
        edge_id: 128,
        SUID: 438,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "436",
        source: "234",
        target: "298",
        shared_name: "toenail metals (interacts with) metabolites",
        shared_interaction: "interacts with",
        name: "toenail metals (interacts with) metabolites",
        interaction: "interacts with",
        edge_id: 129,
        SUID: 436,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "434",
        source: "232",
        target: "346",
        shared_name: "happiness (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "happiness (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 82,
        SUID: 434,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "432",
        source: "230",
        target: "334",
        shared_name: "hassles and uplifts (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "hassles and uplifts (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 83,
        SUID: 432,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "430",
        source: "228",
        target: "266",
        shared_name: "hormone (interacts with) cardiovascular disease",
        shared_interaction: "interacts with",
        name: "hormone (interacts with) cardiovascular disease",
        interaction: "interacts with",
        edge_id: 84,
        SUID: 430,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "428",
        source: "228",
        target: "250",
        shared_name: "hormone (interacts with) diabetes",
        shared_interaction: "interacts with",
        name: "hormone (interacts with) diabetes",
        interaction: "interacts with",
        edge_id: 85,
        SUID: 428,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "426",
        source: "226",
        target: "346",
        shared_name: "hostility (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "hostility (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 86,
        SUID: 426,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "424",
        source: "224",
        target: "326",
        shared_name: "hypertension (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "hypertension (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 87,
        SUID: 424,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "422",
        source: "222",
        target: "346",
        shared_name: "life satisfaction (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "life satisfaction (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 90,
        SUID: 422,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "420",
        source: "220",
        target: "246",
        shared_name:
          "metabolic syndrome component (interacts with) periodontal disease progression",
        shared_interaction: "interacts with",
        name: "metabolic syndrome component (interacts with) periodontal disease progression",
        interaction: "interacts with",
        edge_id: 91,
        SUID: 420,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "418",
        source: "220",
        target: "218",
        shared_name: "metabolic syndrome component (interacts with) tooth loss",
        shared_interaction: "interacts with",
        name: "metabolic syndrome component (interacts with) tooth loss",
        interaction: "interacts with",
        edge_id: 92,
        SUID: 418,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "416",
        source: "216",
        target: "268",
        shared_name: "occupation (interacts with) bone lead",
        shared_interaction: "interacts with",
        name: "occupation (interacts with) bone lead",
        interaction: "interacts with",
        edge_id: 97,
        SUID: 416,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "414",
        source: "214",
        target: "334",
        shared_name: "openness to experiences (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "openness to experiences (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 98,
        SUID: 414,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "412",
        source: "212",
        target: "346",
        shared_name: "optimism (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "optimism (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 99,
        SUID: 412,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "410",
        source: "212",
        target: "210",
        shared_name:
          "optimism (interacts with) endothelial dysfunction markers",
        shared_interaction: "interacts with",
        name: "optimism (interacts with) endothelial dysfunction markers",
        interaction: "interacts with",
        edge_id: 100,
        SUID: 410,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "408",
        source: "212",
        target: "310",
        shared_name: "optimism (interacts with) inflammation biomarkers",
        shared_interaction: "interacts with",
        name: "optimism (interacts with) inflammation biomarkers",
        interaction: "interacts with",
        edge_id: 101,
        SUID: 408,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "406",
        source: "212",
        target: "340",
        shared_name: "optimism (interacts with) leukocyte telomere length",
        shared_interaction: "interacts with",
        name: "optimism (interacts with) leukocyte telomere length",
        interaction: "interacts with",
        edge_id: 102,
        SUID: 406,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "404",
        source: "212",
        target: "208",
        shared_name:
          "optimism (interacts with) leukocyte telomere length change rate",
        shared_interaction: "interacts with",
        name: "optimism (interacts with) leukocyte telomere length change rate",
        interaction: "interacts with",
        edge_id: 103,
        SUID: 404,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "402",
        source: "206",
        target: "340",
        shared_name: "pessimism (interacts with) leukocyte telomere length",
        shared_interaction: "interacts with",
        name: "pessimism (interacts with) leukocyte telomere length",
        interaction: "interacts with",
        edge_id: 104,
        SUID: 402,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "400",
        source: "206",
        target: "208",
        shared_name:
          "pessimism (interacts with) leukocyte telomere length change rate",
        shared_interaction: "interacts with",
        name: "pessimism (interacts with) leukocyte telomere length change rate",
        interaction: "interacts with",
        edge_id: 105,
        SUID: 400,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "398",
        source: "204",
        target: "334",
        shared_name: "psychosocial stressors (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "psychosocial stressors (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 106,
        SUID: 398,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "396",
        source: "202",
        target: "346",
        shared_name: "relative humidity (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "relative humidity (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 107,
        SUID: 396,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "394",
        source: "202",
        target: "338",
        shared_name: "relative humidity (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "relative humidity (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 108,
        SUID: 394,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "392",
        source: "200",
        target: "332",
        shared_name: "road proximity (interacts with) air pollution",
        shared_interaction: "interacts with",
        name: "road proximity (interacts with) air pollution",
        interaction: "interacts with",
        edge_id: 109,
        SUID: 392,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "390",
        source: "198",
        target: "266",
        shared_name: "self-regulation (interacts with) cardiovascular disease",
        shared_interaction: "interacts with",
        name: "self-regulation (interacts with) cardiovascular disease",
        interaction: "interacts with",
        edge_id: 110,
        SUID: 390,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "388",
        source: "196",
        target: "194",
        shared_name: "sleep (interacts with) alzheimer disease biomarkers",
        shared_interaction: "interacts with",
        name: "sleep (interacts with) alzheimer disease biomarkers",
        interaction: "interacts with",
        edge_id: 111,
        SUID: 388,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "386",
        source: "192",
        target: "346",
        shared_name: "smoking (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "smoking (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 112,
        SUID: 386,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "384",
        source: "192",
        target: "348",
        shared_name: "smoking (interacts with) cholesterol level",
        shared_interaction: "interacts with",
        name: "smoking (interacts with) cholesterol level",
        interaction: "interacts with",
        edge_id: 113,
        SUID: 384,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "382",
        source: "190",
        target: "344",
        shared_name:
          "solar and geomagnetic activity (interacts with) blood pressure",
        shared_interaction: "interacts with",
        name: "solar and geomagnetic activity (interacts with) blood pressure",
        interaction: "interacts with",
        edge_id: 114,
        SUID: 382,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "380",
        source: "190",
        target: "188",
        shared_name:
          "solar and geomagnetic activity (interacts with) white blood cell counts",
        shared_interaction: "interacts with",
        name: "solar and geomagnetic activity (interacts with) white blood cell counts",
        interaction: "interacts with",
        edge_id: 115,
        SUID: 380,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "378",
        source: "186",
        target: "334",
        shared_name: "stressful life events (interacts with) mortality",
        shared_interaction: "interacts with",
        name: "stressful life events (interacts with) mortality",
        interaction: "interacts with",
        edge_id: 116,
        SUID: 378,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "376",
        source: "184",
        target: "346",
        shared_name: "temperature (interacts with) DNAmethylation",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) DNAmethylation",
        interaction: "interacts with",
        edge_id: 117,
        SUID: 376,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "374",
        source: "184",
        target: "326",
        shared_name: "temperature (interacts with) cognitive function",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) cognitive function",
        interaction: "interacts with",
        edge_id: 118,
        SUID: 374,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "372",
        source: "184",
        target: "324",
        shared_name: "temperature (interacts with) electrocardiogram",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) electrocardiogram",
        interaction: "interacts with",
        edge_id: 119,
        SUID: 372,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "370",
        source: "184",
        target: "316",
        shared_name:
          "temperature (interacts with) incident abnormal cardiac conductivity",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) incident abnormal cardiac conductivity",
        interaction: "interacts with",
        edge_id: 120,
        SUID: 370,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "368",
        source: "184",
        target: "312",
        shared_name: "temperature (interacts with) incident metabolic syndrome",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) incident metabolic syndrome",
        interaction: "interacts with",
        edge_id: 121,
        SUID: 368,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "366",
        source: "184",
        target: "338",
        shared_name: "temperature (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 122,
        SUID: 366,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "364",
        source: "184",
        target: "300",
        shared_name:
          "temperature (interacts with) metabolic syndrome components",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) metabolic syndrome components",
        interaction: "interacts with",
        edge_id: 123,
        SUID: 364,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "362",
        source: "184",
        target: "298",
        shared_name: "temperature (interacts with) metabolites",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) metabolites",
        interaction: "interacts with",
        edge_id: 124,
        SUID: 362,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "360",
        source: "184",
        target: "336",
        shared_name: "temperature (interacts with) mitochondrial DNA",
        shared_interaction: "interacts with",
        name: "temperature (interacts with) mitochondrial DNA",
        interaction: "interacts with",
        edge_id: 125,
        SUID: 360,
        selected: false,
      },
      selected: false,
    },
    {
      data: {
        id: "358",
        source: "182",
        target: "338",
        shared_name: "tocopherol levels (interacts with) lung function",
        shared_interaction: "interacts with",
        name: "tocopherol levels (interacts with) lung function",
        interaction: "interacts with",
        edge_id: 126,
        SUID: 358,
        selected: false,
      },
      selected: false,
    },
  ],
};

export default elements;
